version: '3'
services:
  docker-mysql:
    image: mysql:5.7
    ports:
      - "3308:3306"
    restart: always
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: air_companies
      MYSQL_USER: aircompanies
      MYSQL_PASSWORD: aircompanies
      MYSQL_ROOT_PASSWORD: root

  air-companies-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    restart: always
    depends_on:
      - docker-mysql